name: Check & Build & Release
run-name: Check & Build & Release (${{ github.ref_name }})

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'src/**'
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  check-build:
    name: Check & Build
    uses: ./.github/workflows/check-build.yml
    secrets: inherit

  release:
    name: Release
    needs: ['check-build']
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full commit history is required as the release tag name is based on commit count
          fetch-depth: 0
          # Tags aren't needed though
          fetch-tags: false
      - name: Prepare the release tag name
        id: tag
        run: echo tag=snapshot-$(git rev-list --count main) >> $GITHUB_OUTPUT
      - name: Prepare the release description
        # Looks like:
        # ```
        # Full commit message
        # ```
        run: |
          echo '```' >> release-body
          git log --pretty=%B -1 >> release-body
          sed -i '$d' release-body
          echo '```' >> release-body
      - name: Prepare the release asset file name
        id: asset-file-name
        run: echo name="${{ needs.check-build.outputs.owner-repo }}-${{ steps.tag.outputs.tag }}.zip" >> $GITHUB_OUTPUT
      - name: Download the build artifact
        run: |
          curl -L \
            -o ${{ steps.asset-file-name.outputs.name }} \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ needs.check-build.outputs.artifact-id }}/zip
      - name: Create a new release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          body_path: release-body
          files: ${{ steps.asset-file-name.outputs.name }}
